# Generated by Django 5.0.6 on 2026-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('profile', models.CharField(choices=[('individual', 'Individual investor'), ('family_office', 'Family office'), ('fund', 'Fund / institution'), ('developer', 'Developer / broker')], default='individual', max_length=32)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_currency', models.CharField(default='EUR', max_length=3)),
                ('markets_of_interest', models.CharField(blank=True, help_text='Free text: countries or cities the investor cares about.', max_length=500)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Investor inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
