# Generated by Django 5.1.15 on 2026-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=300)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-count'],
                'constraints': [models.UniqueConstraint(fields=('date', 'path'), name='uniq_pageview_date_path')],
            },
        ),
        migrations.CreateModel(
            name='SiteStats',
            fields=[
            ],
            options={
                'verbose_name': 'Site statistics',
                'verbose_name_plural': 'Site statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.dailypageview',),
        ),
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(max_length=40)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'visitor_hash'), name='uniq_visitor_date_hash')],
            },
        ),
    ]
