# Generated by Django 5.0.6 on 2026-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmetric',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Explainability payload: factor scores, strengths, risks.'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_agency',
            field=models.CharField(blank=True, help_text='Brokerage or developer marketing this listing.', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Internal or MLS-style reference shown to investors.', max_length=64),
        ),
    ]
