# Generated by Django 5.1.15 on 2026-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text="Listing details checked by Vivalty's editorial desk."),
        ),
    ]
