# Generated by Django 5.0.6 on 2026-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_mark_featured_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12),
        ),
    ]
