# Generated by Django 5.0.6 on 2026-05-03 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_advisor', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null = anonymous session keyed by client cookie.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_advisor.aiconversationsession'),
        ),
        migrations.AddIndex(
            model_name='aiconversationsession',
            index=models.Index(fields=['user', '-updated_at'], name='ai_advisor__user_id_e52eab_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_advisor__session_1c4903_idx'),
        ),
    ]
