# Generated by Django 5.0.6 on 2026-05-03 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO-3166-1 alpha-2', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(default='EUR', help_text='ISO-4217', max_length=3)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
                ('base_roi_min', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('base_roi_max', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('base_rental_yield', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('base_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('base_trend', models.CharField(choices=[('growth', 'Growth'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=10)),
                ('base_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('summary', models.TextField(blank=True, help_text='Short market overview shown to investors and to the AI.')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_price_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_rental_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('demand', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('trend', models.CharField(blank=True, choices=[('growth', 'Growth'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=10, null=True)),
                ('risk', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('investment_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100', null=True)),
                ('summary', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['country__name', 'name'],
                'indexes': [models.Index(fields=['country', 'name'], name='geo_city_country_65cc4c_idx'), models.Index(fields=['investment_score'], name='geo_city_investm_a827c7_idx')],
                'unique_together': {('country', 'slug')},
            },
        ),
    ]
